[tool.poetry]
name = "actions"
version = "0.1.0"
description = "airbyte actions"
authors = ["cpdeethree <conor@airbyte.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dagger-io = "^0.4.0"
python-dotenv = "^0.21.0"
asyncclick = "^8.1.3.4"
google-cloud-run = "^0.5.0"
pre-commit = "^2.21.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
